export const SET_GEOLOCATION = 'SET_GEOLOCATION';
export const GET_GEO_CODE = 'GET_GEO_CODE';
export const SET_PERSION_INFO = 'SET_PERSION_INFO';
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_PARCELS = 'GET_PARCELS';
export const GET_CURRENCIES = 'GET_CURRENCIES';

export const GET_ALL_ADDRESS = 'GET_ALL_ADDRESS';
export const GET_ALL_TRANSPORT_REQUESTS = 'GET_ALL_TRANSPORT_REQUESTS';
